Np 2819 fetch person from orcid
BIBSYSDEV/nva-cristin-service pull request #102
Opened 2021-12-08 14:00 UTC by torarnet

A little skeptical about how to set URI to cristin test instance, as orcid fetch is not in cristin production yet

2021-12-08 14:23 UTC, brinxmat requested changes

2021-12-08 14:23 UTC, brinxmat commented on cristin-commons/src/main/java/no/unit/nva/cristin/model/Constants.java
> +    public static final Pattern ORCID_PATTERN = Pattern.compile("[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{4}");
I think that the ORCID pattern should be validated properly as "Both ORCID and ISNI use 16-character identifiers, using the digits 0–9, and separated into groups of four by hyphens. The final character, which may also be a letter "X" representing the value "10" (for example, Stephen Hawking's ORCID iD is https://orcid.org/0000-0002-9079-593X), is a MOD 11-2 check digit conforming to the ISO/IEC 7064:2003 standard."

2021-12-09 08:53 UTC, axthosarouris approved these changes

2021-12-09 10:06 UTC, brinxmat approved these changes

2021-12-09 10:12 UTC, merged