Np 3560 handler client post person
BIBSYSDEV/nva-cristin-service pull request #125
Opened 2022-01-24 16:13 UTC by torarnet

Will add authenticated cristin client later in review, and also remove commented karate action before merge. If this PR is too large, I can try to split it into smaller PR, but then I have to use more time to do so

2022-01-24 16:30 UTC, brinxmat requested changes

2022-01-24 16:30 UTC, brinxmat commented on cristin-person/src/main/java/no/unit/nva/cristin/person/create/CreateCristinPersonHandler.java
> +        if (Objects.isNull(input)) {
Static import

2022-01-25 12:39 UTC, svenngjeto approved these changes

2022-01-26 11:19 UTC, brinxmat submitted a review, later dismissed

2022-01-27 10:50 UTC, axthosarouris approved these changes

2022-01-27 11:50 UTC, merged