Np 6913 api client patch person
BIBSYSDEV/nva-cristin-service pull request #162
Opened 2022-03-21 11:31 UTC by torarnet

2022-03-21 12:34 UTC, brinxmat requested changes

2022-03-23 07:36 UTC, svenngjeto commented on cristin-person/src/main/java/no/unit/nva/cristin/person/update/UpdateCristinPersonApiClient.java
> +    public String updatePersonInCristin(String personId, ObjectNode request) throws ApiGatewayException {
This could be Void?

2022-03-23 08:31 UTC, brinxmat approved these changes

2022-03-23 12:25 UTC, brinxmat approved these changes

2022-03-24 08:46 UTC, svenngjeto approved these changes

2022-03-24 12:20 UTC, merged