Np 9238 get person with employments
BIBSYSDEV/nva-cristin-service pull request #207
Opened 2022-08-05 12:32 UTC by torarnet

2022-08-15 10:11 UTC, axthosarouris requested changes

2022-08-15 10:11 UTC, axthosarouris commented on cristin-person/src/test/java/no/unit/nva/cristin/person/handler/FetchCristinPersonHandlerTest.java
> +        var actual = sendQuery(EMPTY_MAP, VALID_PATH_PARAM).getBodyObject(Person.class);
Is `sendQuery` a `sendUnauthorizedQuery`?

2022-08-15 10:11 UTC, axthosarouris commented on cristin-person/src/test/java/no/unit/nva/cristin/person/handler/FetchCristinPersonHandlerTest.java
> +        var actual = sendQuery(EMPTY_MAP, VALID_PATH_PARAM).getBodyObject(Person.class);
what is the emptyMap, is it empty QueryParameters?

2022-08-15 10:11 UTC, axthosarouris commented on cristin-person/src/test/java/no/unit/nva/cristin/person/handler/FetchCristinPersonHandlerTest.java
> +    void shouldNotReturnEmploymentsWhenNotAuthorized() throws IOException, ApiGatewayException {
"shouldNotRequestEmploymentsFromProxiedServerWhenClientIsNotAuthorized" ?

2022-08-15 10:11 UTC, axthosarouris commented on cristin-person/src/test/java/no/unit/nva/cristin/person/handler/FetchCristinPersonHandlerTest.java
> +        apiClient = spy(apiClient);
Suggestion:
```
 @Test
    void shouldReturnEmploymentsWhenAuthorized() throws IOException, ApiGatewayException {
        setUpApiClientToRespondToPersonAndEmploymentRequestsWhenRequestIsAuthorizedAndPersonHasEmployment();
    
        handler = new FetchCristinPersonHandler(apiClient, environment);
        var actual = sendAuthorizedQuery(EDIT_OWN_INSTITUTION_USERS).getBodyObject(Person.class);

        assertThat(actual.getEmployments().size(), equalTo(EXPECTED_EMPLOYMENT_SIZE_WHEN_AUTHORIZED));
    }

 private void setUpApiClientToRespondToPersonAndEmploymentRequestsWhenRequestIsAuthorizedAndPersonHasEmployment() throws ApiGatewayException {
        apiClient = spy(apiClient);
        var cristinPersonUri = URI.create(EXPECTED_CRISTIN_URI_WITH_IDENTIFIER);
        doReturn(getResponseWithoutEmployment()).when(apiClient).fetchGetResultWithAuthentication(cristinPersonUri);
        var cristinPersonEmploymentsUri = URI.create(EXPECTED_CRISTIN_EMPLOYMENTS_URI_WITH_IDENTIFIER);
        doReturn(getResponseWithOnlyEmployments()).when(apiClient)
            .fetchGetResultWithAuthentication(cristinPersonEmploymentsUri);
    }


```

2022-08-15 10:11 UTC, axthosarouris commented on cristin-person/src/test/java/no/unit/nva/cristin/person/handler/FetchCristinPersonHandlerTest.java
> +    void shouldReturnOkEvenWhenEmploymentsAreEmpty() throws ApiGatewayException, IOException {
do the same here as suggested above

2022-08-15 10:11 UTC, axthosarouris commented on cristin-person/src/test/java/no/unit/nva/cristin/person/handler/FetchCristinPersonHandlerTest.java
> +    void shouldNotReturnEmploymentsWhenNotHavingRequiredAccessRight() throws IOException, ApiGatewayException {
use the "setUpApiClientToRespondToPersonAndEmploymentRequestsWhenRequestIsAuthorizedAndPersonHasEmployment" method

2022-08-15 14:06 UTC, torarnet commented
There will be changes in how employment data is returned from the Cristin Api. With the new changes employment data is included in the original Person GET, meaning we don't have to do an extra request. I am considering closing this PR.

2022-08-16 06:59 UTC, brinxmat reviewed
See previous reviewer's comments

2022-08-18 13:10 UTC, closed without merging