https://unit.atlassian.net/browse/NP-29836
BIBSYSDEV/nva-cristin-service pull request #254
Opened 2023-01-20 13:13 UTC by StigNorland

errorMessage now contains hint of what happened.

2023-01-20 13:19 UTC, torarnet submitted a review, later dismissed

2023-01-20 13:58 UTC, ketilaa requested changes
Unngå bruk av ordinal for enums.

2023-01-20 13:58 UTC, ketilaa commented on cristin-project/src/main/java/no/unit/nva/cristin/projects/create/CreateCristinProjectValidator.java
> +        if (validatedResult.ordinal() > ValidatedResult.Ok.ordinal()) {
Er ikke dette sårbart ift at noen endrer rekkefølgen en gang? Er ikke `if (!validatedResult.equals(ValidatedResult.Ok))` bedre?

2023-01-20 14:25 UTC, ketilaa submitted a review, later dismissed

2023-01-23 09:12 UTC, torarnet submitted a review, later dismissed

2023-01-23 10:26 UTC, StigNorland commented on cristin-project/src/main/java/no/unit/nva/cristin/projects/create/CreateCristinProjectValidator.java
> +        Empty(" (project data required)"),
I'll fix it

2023-01-23 11:45 UTC, ketilaa commented on cristin-project/src/main/java/no/unit/nva/cristin/projects/create/CreateCristinProjectValidator.java
> +        if (!validatedResult.contains(ValidatedResult.Ok)) {
Nå kan du kanskje fjerne status ok, og anta at alt er ok dersom settet er tomt? Nå blir det litt utydelig oppførsel. Skal vi virkelig ignorere feil som rapporteres sammen med Ok?

2023-01-23 12:36 UTC, StigNorland commented on cristin-project/src/main/java/no/unit/nva/cristin/projects/create/CreateCristinProjectValidator.java
> +        if (!validatedResult.contains(ValidatedResult.Ok)) {
Koden returnerte kun ok, om settet var tomt.
Jeg har flyttet testen ut av validateProjectInput, og fjernet OK.

2023-01-23 12:46 UTC, ketilaa approved these changes

2023-01-23 14:20 UTC, merged