Migrate name to labels, adding context-object
BIBSYSDEV/nva-cristin-service pull request #305
Opened 2023-06-21 10:50 UTC by brinxmat

- name is labels
- add context object

2023-06-21 10:58 UTC, torarnet reviewed
Update karate tests with new field name and validate context object is displayed correctly

2023-06-21 11:20 UTC, torarnet commented on cristin-funding/src/main/java/no/unit/nva/cristin/funding/sources/model/nva/FundingSource.java
>      @JsonProperty(NAME_FIELD)
you forgot to update name tag

2023-06-21 11:21 UTC, torarnet requested changes
You forgot to update field's name tag. Also, you need to update karate tests

2023-07-13 09:40 UTC, ketilaa commented
@brinxmat Did you forget about this PR? Is it something we should work to complete?

2023-11-09 11:35 UTC, torarnet commented
status @brinxmat ?

2024-05-15 10:05 UTC, merged