Np 45524 add facets to person query
BIBSYSDEV/nva-cristin-service pull request #333
Opened 2023-11-06 17:15 UTC by torarnet

2023-11-06 17:16 UTC, torarnet commented
Will update Karate tests and OpenApi in later commit, everything else is ready for review.

2023-11-07 07:36 UTC, brinxmat requested changes

2023-11-07 07:36 UTC, brinxmat commented on cristin-commons/src/main/java/no/unit/nva/cristin/facet/FacetUriParamAppender.java
> +                map.put(keyValue[0], new ArrayList<>(values));
Name the '&', '=' and ','. The names should be something like QUERY_PARAMETER_DELIMITER, QUERY_PARAMETER_ASSIGNER and QUERY_VALUE_DELIMITER respectively.

2023-11-07 07:36 UTC, brinxmat commented on cristin-commons/src/main/java/no/unit/nva/cristin/facet/FacetUriParamAppender.java
> +            combinedMap.put(entry.getKey(), String.join(",", uniqueValues));
I guess re-use the constant from above

2023-11-07 07:36 UTC, brinxmat commented on cristin-commons/src/main/java/no/unit/nva/cristin/model/query/CristinFacetKey.java
> +        }
Maybe have method in CristinFacet's extensions to return the value

2023-11-07 07:36 UTC, brinxmat commented on cristin-commons/src/test/java/no/unit/nva/cristin/facet/FacetUriParamAppenderTest.java
> +        CristinFacet cristinFacet = new CristinSectorFacet("UC", null);
`var` here and elsewhere

2023-11-07 07:36 UTC, brinxmat commented on cristin-commons/src/test/java/no/unit/nva/cristin/facet/FacetUriParamAppenderTest.java
> +public class FacetUriParamAppenderTest {
package private

2023-11-07 07:36 UTC, brinxmat commented on cristin-commons/src/test/java/no/unit/nva/cristin/facet/CristinFacetUriParamAppenderTest.java
> +public class CristinFacetUriParamAppenderTest {
package private

2023-11-07 14:06 UTC, brinxmat approved these changes

2023-11-07 14:08 UTC, merged