Np 47035 small project improvements
BIBSYSDEV/nva-cristin-service pull request #391
Opened 2024-06-26 12:09 UTC by torarnet

2024-06-27 06:31 UTC, brinxmat requested changes

2024-06-27 06:31 UTC, brinxmat commented on cristin-project/src/main/java/no/unit/nva/cristin/projects/model/nva/NvaProjectBuilder.java
> +                   .filter(this::hasData)
It's also likely the case that everywhere you use the Optional::ofNullable construct inline points to a case where you can pull the Optional over to the called method, so `public Optional<String> getCristinProjectId() {…}`

2024-06-27 09:06 UTC, anetteOlli approved these changes

2024-07-01 11:55 UTC, brinxmat approved these changes

2024-07-01 11:56 UTC, merged