np-47138: update to java 21
BIBSYSDEV/nva-cristin-service pull request #408
Opened 2024-09-24 07:46 UTC by torarnet

2024-09-24 07:46 UTC, torarnet commented
Still issues with PMD not working, but that should maybe be fixed in separate PR

2024-09-24 07:50 UTC, ketilaa submitted a review, later dismissed

2024-09-26 14:08 UTC, brinxmat requested changes

2024-09-26 14:08 UTC, brinxmat commented on buildSrc/build.gradle
> +java.targetCompatibility = JavaVersion.VERSION_21
```
java {
    java.sourceCompatibility = JavaVersion.VERSION_21
    java.targetCompatibility = JavaVersion.VERSION_21
}
```

2024-10-01 10:27 UTC, brinxmat approved these changes

2024-10-01 10:58 UTC, merged